version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: accidents_api:latest
    environment:
      - MODEL_PATH=/app/model/model.pkl
      - ADMIN_TOKEN=${ADMIN_TOKEN:-change-me-secure-token}
    volumes:
      - ./outputs:/app/model:ro
    ports:
      - "8000:80"
    depends_on:
      - mlflow
    networks:
      - appnet

  trainer:
    build:
      context: .
      dockerfile: Dockerfile.train
    image: accidents_trainer:latest
    volumes:
      - ./data:/data
      - ./outputs:/outputs
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
    depends_on:
      - mlflow
    networks:
      - appnet

  mlflow:
    image: python:3.10-slim
    command: sh -c "pip install mlflow && mlflow server \
      --backend-store-uri sqlite:///mlflow.db \
      --default-artifact-root /mlflow/artifacts \
      --host 0.0.0.0 --port 5001 \
      --serve-artifacts"
    volumes:
      - ./mlflow:/mlflow
    ports:
      - "5001:5001"
    networks:
      - appnet

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - appnet

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
